/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package InterfaceGrafica;

/**
 *
 * @author manoel
 */
public class TelaPrincipalConsultas extends javax.swing.JFrame {

    private TelaAgendarConsultas telaAgendarConsultas;
    private TelaAtualizarConsulta telaAtualizarConsulta;
    private TelaDeletarConsulta telaDeletarConsulta;
    private TelaFiltrarConsultas telaFiltrarConsultas;
    
    public TelaPrincipalConsultas() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        agendatBotao = new javax.swing.JButton();
        filtrarBotato = new javax.swing.JButton();
        atualizarBotao = new javax.swing.JButton();
        deletarBota = new javax.swing.JButton();
        SairBotao = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Consultas");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(170, 170, 170)
                .addComponent(jLabel1)
                .addContainerGap(183, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(15, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 400, 40));

        agendatBotao.setText("agendar consulta");
        agendatBotao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                agendatBotaoActionPerformed(evt);
            }
        });
        getContentPane().add(agendatBotao, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 90, -1, -1));

        filtrarBotato.setText("filtrar consultas");
        filtrarBotato.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                filtrarBotatoActionPerformed(evt);
            }
        });
        getContentPane().add(filtrarBotato, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 140, 120, -1));

        atualizarBotao.setText("atualizar consulta");
        atualizarBotao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                atualizarBotaoActionPerformed(evt);
            }
        });
        getContentPane().add(atualizarBotao, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 190, -1, -1));

        deletarBota.setText("Excluir consulta");
        deletarBota.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deletarBotaActionPerformed(evt);
            }
        });
        getContentPane().add(deletarBota, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 240, 120, -1));

        SairBotao.setText("Sair");
        SairBotao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SairBotaoActionPerformed(evt);
            }
        });
        getContentPane().add(SairBotao, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 270, 80, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void agendatBotaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_agendatBotaoActionPerformed
        this.telaAgendarConsultas = new TelaAgendarConsultas();
        this.telaAgendarConsultas.setVisible(true);
    }//GEN-LAST:event_agendatBotaoActionPerformed

    private void filtrarBotatoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_filtrarBotatoActionPerformed
        this.telaFiltrarConsultas = new TelaFiltrarConsultas();
        this.telaFiltrarConsultas.setVisible(true);
    }//GEN-LAST:event_filtrarBotatoActionPerformed

    private void atualizarBotaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_atualizarBotaoActionPerformed
        this.telaAtualizarConsulta = new TelaAtualizarConsulta();
        this.telaAtualizarConsulta.setVisible(true);
    }//GEN-LAST:event_atualizarBotaoActionPerformed

    private void deletarBotaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deletarBotaActionPerformed
        this.telaDeletarConsulta = new TelaDeletarConsulta();
        this.telaDeletarConsulta.setVisible(true);
    }//GEN-LAST:event_deletarBotaActionPerformed

    private void SairBotaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SairBotaoActionPerformed
         dispose();      
    }//GEN-LAST:event_SairBotaoActionPerformed

   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton SairBotao;
    private javax.swing.JButton agendatBotao;
    private javax.swing.JButton atualizarBotao;
    private javax.swing.JButton deletarBota;
    private javax.swing.JButton filtrarBotato;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
