/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package InterfaceGrafica;

import br.upe.poo.clinica.entidades.Pacientes;
import br.upe.poo.clinica.regraNegocio.ExceptionRegraNegocioAtualizarPacientes;
import br.upe.poo.clinica.regraNegocio.ExceptionRegraNegocioPacienteBuscarPaciente;
import br.upe.poo.clinica.regraNegocio.Fachada;
import br.upe.poo.clinica.regraNegocio.FachadaImplementa;
import java.sql.Date;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author manoel
 */
public class TelaAtualizarPacientes extends javax.swing.JFrame {

     private Pacientes paciente;
     private  String sexo;
    /**
     * Creates new form TelaAtualizar
     */
    public TelaAtualizarPacientes() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        nomePaciente = new javax.swing.JLabel();
        nomeText = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        enderecoText = new javax.swing.JTextField();
        telefoneText = new javax.swing.JTextField();
        dataNasText = new javax.swing.JFormattedTextField();
        sexoJText = new javax.swing.JComboBox<>();
        AtualizarjButton1 = new javax.swing.JButton();
        SairjButton1 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        cpfJtext = new javax.swing.JTextField();
        filtrarjButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Atualizar pacientes");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(154, 154, 154)
                .addComponent(jLabel1)
                .addContainerGap(155, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(15, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 400, 40));

        nomePaciente.setText("nome");
        getContentPane().add(nomePaciente, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, 40, -1));

        nomeText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nomeTextActionPerformed(evt);
            }
        });
        getContentPane().add(nomeText, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 80, 250, -1));

        jLabel2.setText("endereco");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, -1, -1));

        jLabel3.setText("telefone");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 150, -1, -1));

        jLabel4.setText("sexo");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 190, -1, -1));

        jLabel5.setText("data de nascimento");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 230, -1, -1));
        getContentPane().add(enderecoText, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 110, 250, -1));
        getContentPane().add(telefoneText, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 150, 110, -1));

        dataNasText.setText("  /  /    ");
        getContentPane().add(dataNasText, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 230, 70, -1));

        sexoJText.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Masculino", "Feminino" }));
        sexoJText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sexoJTextActionPerformed(evt);
            }
        });
        getContentPane().add(sexoJText, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 190, -1, -1));

        AtualizarjButton1.setText("salvar");
        AtualizarjButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AtualizarjButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(AtualizarjButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 270, -1, -1));

        SairjButton1.setText("sair");
        SairjButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SairjButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(SairjButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 270, 60, -1));

        jLabel6.setText("digite cpf do paciente");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, -1, -1));
        getContentPane().add(cpfJtext, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 40, 130, -1));

        filtrarjButton1.setText("Filtrar");
        filtrarjButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                filtrarjButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(filtrarjButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 40, -1, 20));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void nomeTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nomeTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nomeTextActionPerformed

    private void AtualizarjButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AtualizarjButton1ActionPerformed
                
            Fachada fachada = new FachadaImplementa();
              this.paciente.setEndereco(enderecoText.getText());
              this.paciente.setNome(nomeText.getText());
              this.paciente.setSexo(sexo);
              this.paciente.setTelefone(telefoneText.getText());
              this.paciente.setDataNascimento(dataNasText.getText());
         try {
             fachada.atualizarPaciente(this.paciente);
         } catch (ExceptionRegraNegocioAtualizarPacientes ex) {
             Logger.getLogger(TelaAtualizarPacientes.class.getName()).log(Level.SEVERE, null, ex);
         }
    
    
    }//GEN-LAST:event_AtualizarjButton1ActionPerformed

    private void sexoJTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sexoJTextActionPerformed
        sexo = new String(); 
         if(sexoJText.getSelectedIndex()==0) {
             sexo = "masculino";
         }
         else {
             sexo = "feminino";
    }//GEN-LAST:event_sexoJTextActionPerformed
    }
    private void filtrarjButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_filtrarjButton1ActionPerformed
           this.paciente = new Pacientes();
           Long cpf = new Long(11);
           cpf = Long.parseLong(cpfJtext.getText());
            FachadaImplementa fachada = new FachadaImplementa();
         try {
            this.paciente = fachada.buscarPacienteCpf(cpf);
         } catch (ExceptionRegraNegocioPacienteBuscarPaciente ex) {
             Logger.getLogger(TelaAtualizarPacientes.class.getName()).log(Level.SEVERE, null, ex);
         }
    }//GEN-LAST:event_filtrarjButton1ActionPerformed

    private void SairjButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SairjButton1ActionPerformed
dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_SairjButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AtualizarjButton1;
    private javax.swing.JButton SairjButton1;
    private javax.swing.JTextField cpfJtext;
    private javax.swing.JFormattedTextField dataNasText;
    private javax.swing.JTextField enderecoText;
    private javax.swing.JButton filtrarjButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel nomePaciente;
    private javax.swing.JTextField nomeText;
    private javax.swing.JComboBox<String> sexoJText;
    private javax.swing.JTextField telefoneText;
    // End of variables declaration//GEN-END:variables
}
