/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package InterfaceGrafica;

import br.upe.poo.clinica.entidades.Consultas;
import br.upe.poo.clinica.entidades.Medicos;
import br.upe.poo.clinica.entidades.Pacientes;
import br.upe.poo.clinica.regraNegocio.ExceptionRegraNegocioAgendarConsultas;
import br.upe.poo.clinica.regraNegocio.ExceptionRegraNegocioBuscarMedicos;
import br.upe.poo.clinica.regraNegocio.ExceptionRegraNegocioPacienteBuscarPaciente;
import br.upe.poo.clinica.regraNegocio.Fachada;
import br.upe.poo.clinica.regraNegocio.FachadaImplementa;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author manoel
 */
public class TelaAgendarConsultas extends javax.swing.JFrame {

      private String diaConsulta;
      private String horaConsulta;
    
    public TelaAgendarConsultas() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        pacientesText = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        diaText = new javax.swing.JComboBox<>();
        mesText = new javax.swing.JComboBox<>();
        horaText = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        medicoBotao = new javax.swing.JButton();
        pacienteBotao = new javax.swing.JButton();
        medicoText = new javax.swing.JTextField();
        salvarBotao = new javax.swing.JButton();
        sairBotao = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        medicoEscolhioText = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        pacienteSelecionadoText = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Agendar consultas");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(157, 157, 157)
                .addComponent(jLabel1)
                .addContainerGap(94, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(35, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 340, 60));

        pacientesText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pacientesTextActionPerformed(evt);
            }
        });
        getContentPane().add(pacientesText, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 180, 220, -1));

        jLabel2.setText("cpf paciente");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 180, -1, -1));

        jLabel3.setText("dia da consulta");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, -1, -1));

        jLabel4.setText("hora da consulta");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 100, -1, -1));

        diaText.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31" }));
        diaText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                diaTextActionPerformed(evt);
            }
        });
        getContentPane().add(diaText, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 70, -1, -1));

        mesText.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12" }));
        mesText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mesTextActionPerformed(evt);
            }
        });
        getContentPane().add(mesText, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 70, -1, -1));

        horaText.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "O8:00", "O9:00", "10:00", "11:00", "14:00", "15:00", "16:00", "17:00" }));
        horaText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                horaTextActionPerformed(evt);
            }
        });
        getContentPane().add(horaText, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 100, -1, -1));

        jLabel5.setText("cpf do medico");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 140, -1, -1));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "nome Medico", "cpf"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jTable1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTable1KeyTyped(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 10, 450, 90));

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "nome paciente", "cpf paciente"
            }
        ));
        jScrollPane2.setViewportView(jTable2);
        if (jTable2.getColumnModel().getColumnCount() > 0) {
            jTable2.getColumnModel().getColumn(1).setResizable(false);
        }

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 160, -1, 90));

        medicoBotao.setText("filtrar medico");
        medicoBotao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                medicoBotaoActionPerformed(evt);
            }
        });
        getContentPane().add(medicoBotao, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 60, -1, -1));

        pacienteBotao.setText("filtrar paciente");
        pacienteBotao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pacienteBotaoActionPerformed(evt);
            }
        });
        getContentPane().add(pacienteBotao, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 220, -1, -1));
        getContentPane().add(medicoText, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 140, 220, -1));

        salvarBotao.setText("agendar");
        salvarBotao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salvarBotaoActionPerformed(evt);
            }
        });
        getContentPane().add(salvarBotao, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 270, -1, -1));

        sairBotao.setText("sair");
        sairBotao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sairBotaoActionPerformed(evt);
            }
        });
        getContentPane().add(sairBotao, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 270, 70, -1));

        jLabel6.setText("digite nome do medico");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 10, -1, -1));
        getContentPane().add(medicoEscolhioText, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 30, 200, -1));

        jLabel7.setText("digite nome do paciente");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 160, -1, -1));
        getContentPane().add(pacienteSelecionadoText, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 180, 200, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void pacientesTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pacientesTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pacientesTextActionPerformed

    private void jTable1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTable1KeyTyped
       
    }//GEN-LAST:event_jTable1KeyTyped

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        
    }//GEN-LAST:event_jTable1MouseClicked

    private void diaTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_diaTextActionPerformed
        
         
    }//GEN-LAST:event_diaTextActionPerformed

    private void medicoBotaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_medicoBotaoActionPerformed
        Fachada fachada = new FachadaImplementa();
         List<Medicos>medicos = new ArrayList();
        try {
            medicos = fachada.buscarMedicoNome(medicoEscolhioText.getText());
        } catch (ExceptionRegraNegocioBuscarMedicos ex) {
            Logger.getLogger(TelaAgendarConsultas.class.getName()).log(Level.SEVERE, null, ex);
        }
         for(int i = 0; i<medicos.size();i++) {
            jTable1.setValueAt(medicos.get(i).getNome(), i, 0);
            jTable1.setValueAt(medicos.get(i).getCpf(), i, 1);
         }
    }//GEN-LAST:event_medicoBotaoActionPerformed

    private void pacienteBotaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pacienteBotaoActionPerformed
        Fachada fachada = new FachadaImplementa();
         List<Pacientes>pacientes = new ArrayList();
        try {
            pacientes = fachada.buscarPacienteNome(pacienteSelecionadoText.getText());
        } catch (ExceptionRegraNegocioPacienteBuscarPaciente ex) {
            Logger.getLogger(TelaAgendarConsultas.class.getName()).log(Level.SEVERE, null, ex);
        }
         for(int i = 0; i<pacientes.size();i++) {
            jTable2.setValueAt(pacientes.get(i).getNome(), i, 0);
            jTable2.setValueAt(pacientes.get(i).getCpf(), i, 1);
         }

    }//GEN-LAST:event_pacienteBotaoActionPerformed

    private void horaTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_horaTextActionPerformed
        this.horaConsulta = new String();
        this.horaConsulta = String.valueOf(horaText.getSelectedItem());
    }//GEN-LAST:event_horaTextActionPerformed

    private void mesTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mesTextActionPerformed

                
    }//GEN-LAST:event_mesTextActionPerformed

    private void salvarBotaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salvarBotaoActionPerformed
        this.diaConsulta = new String();
        String mes = new String();
        mes = String.valueOf(mesText.getSelectedItem());
        String dia = new String();
        dia = String.valueOf(diaText.getSelectedItem());
        this.diaConsulta = ""+dia+"/"+mes;
        
          Pacientes paciente = new Pacientes();
          Medicos medico = new Medicos();
                  
          Long cpf = new Long(11);cpf = Long.parseLong(pacientesText.getText());
          Long cpfMedico = new Long(10); cpfMedico = Long.parseLong(medicoText.getText());
          Fachada fachada = new FachadaImplementa();
          try {            
              paciente = fachada.buscarPacienteCpf(cpf);
          } catch (ExceptionRegraNegocioPacienteBuscarPaciente ex) {
              Logger.getLogger(TelaAgendarConsultas.class.getName()).log(Level.SEVERE, null, ex);
          }
          try {         
              medico = fachada.buscarMedicoCpf(cpfMedico);
          } catch (ExceptionRegraNegocioBuscarMedicos ex) {
              Logger.getLogger(TelaAgendarConsultas.class.getName()).log(Level.SEVERE, null, ex);
          }
                  Consultas consulta = new Consultas(paciente, this.diaConsulta, this.horaConsulta, medico);
          try {
              fachada.agendarConsulta(consulta);
          } catch (ExceptionRegraNegocioAgendarConsultas ex) {
              Logger.getLogger(TelaAgendarConsultas.class.getName()).log(Level.SEVERE, null, ex);
          }
        
    }//GEN-LAST:event_salvarBotaoActionPerformed

    private void sairBotaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sairBotaoActionPerformed
        dispose();
    }//GEN-LAST:event_sairBotaoActionPerformed

   
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> diaText;
    private javax.swing.JComboBox<String> horaText;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JButton medicoBotao;
    private javax.swing.JTextField medicoEscolhioText;
    private javax.swing.JTextField medicoText;
    private javax.swing.JComboBox<String> mesText;
    private javax.swing.JButton pacienteBotao;
    private javax.swing.JTextField pacienteSelecionadoText;
    private javax.swing.JTextField pacientesText;
    private javax.swing.JButton sairBotao;
    private javax.swing.JButton salvarBotao;
    // End of variables declaration//GEN-END:variables
}
