package InterfaceGrafica;

import br.upe.poo.clinica.entidades.Usuarios;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author manoel
 */
public class TelaPrincipalAdministradores extends javax.swing.JFrame {

      private TelaPrincipalPacientes telaPacientes;
      private TelaPrincipalMedicos telaMedicos;
      private TelaUsuarios usuarios;
    /**
     * Creates new form TelaPrincipalAdministradores
     */
    public TelaPrincipalAdministradores() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        pacientesBotao = new javax.swing.JButton();
        MedicosBotao = new javax.swing.JButton();
        usuariosBotao = new javax.swing.JButton();
        sairBotao = new javax.swing.JButton();

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Tela administradores");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(163, 163, 163)
                .addComponent(jLabel1)
                .addContainerGap(138, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(35, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 400, 60));

        pacientesBotao.setText("Pacientes");
        pacientesBotao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pacientesBotaoActionPerformed(evt);
            }
        });
        getContentPane().add(pacientesBotao, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 80, -1, -1));

        MedicosBotao.setText("medicos");
        MedicosBotao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MedicosBotaoActionPerformed(evt);
            }
        });
        getContentPane().add(MedicosBotao, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 140, -1, -1));

        usuariosBotao.setText("usuarios");
        usuariosBotao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usuariosBotaoActionPerformed(evt);
            }
        });
        getContentPane().add(usuariosBotao, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 210, -1, -1));

        sairBotao.setText("Sair");
        sairBotao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sairBotaoActionPerformed(evt);
            }
        });
        getContentPane().add(sairBotao, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 270, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void pacientesBotaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pacientesBotaoActionPerformed
        this.telaPacientes = new TelaPrincipalPacientes();
          this.telaPacientes.setVisible(true);
    }//GEN-LAST:event_pacientesBotaoActionPerformed

    private void MedicosBotaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MedicosBotaoActionPerformed
       this.telaMedicos = new TelaPrincipalMedicos();
        this.telaMedicos.setVisible(true);
    }//GEN-LAST:event_MedicosBotaoActionPerformed

    private void sairBotaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sairBotaoActionPerformed
        dispose();
    }//GEN-LAST:event_sairBotaoActionPerformed

    private void usuariosBotaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usuariosBotaoActionPerformed
        this.usuarios = new TelaUsuarios();
        this.usuarios.setVisible(true);
    }//GEN-LAST:event_usuariosBotaoActionPerformed

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton MedicosBotao;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JButton pacientesBotao;
    private javax.swing.JButton sairBotao;
    private javax.swing.JButton usuariosBotao;
    // End of variables declaration//GEN-END:variables
}
