/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package InterfaceGrafica;

/**
 *
 * @author manoel
 */
public class TelaPrincipalClinica extends javax.swing.JFrame {

      private TelaPrincipalPacientes telaPacientes;
      private TelaPrincipalMedicos telaMedicos;
    
    public TelaPrincipalClinica() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        PacientesBotao = new javax.swing.JButton();
        MedicosBotao = new javax.swing.JButton();
        sairBotao = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("Clinica");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(178, 178, 178)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(151, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(27, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 400, 60));

        PacientesBotao.setText("Pacientes");
        PacientesBotao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PacientesBotaoActionPerformed(evt);
            }
        });
        getContentPane().add(PacientesBotao, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, -1, -1));

        MedicosBotao.setText("Medicos");
        MedicosBotao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MedicosBotaoActionPerformed(evt);
            }
        });
        getContentPane().add(MedicosBotao, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 160, 80, -1));

        sairBotao.setText("Sair");
        sairBotao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sairBotaoActionPerformed(evt);
            }
        });
        getContentPane().add(sairBotao, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 250, 100, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void PacientesBotaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PacientesBotaoActionPerformed
          this.telaPacientes = new TelaPrincipalPacientes();
          this.telaPacientes.setVisible(true);
    }//GEN-LAST:event_PacientesBotaoActionPerformed

    private void MedicosBotaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MedicosBotaoActionPerformed
        this.telaMedicos = new TelaPrincipalMedicos();
        this.telaMedicos.setVisible(true);
    }//GEN-LAST:event_MedicosBotaoActionPerformed

    private void sairBotaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sairBotaoActionPerformed
       dispose();
    }//GEN-LAST:event_sairBotaoActionPerformed

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton MedicosBotao;
    private javax.swing.JButton PacientesBotao;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton sairBotao;
    // End of variables declaration//GEN-END:variables
}
